// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  Plasmic上传视频,
  Default上传视频Props
} from "./plasmic/c_vevaluate/Plasmic\u4E0A\u4F20\u89C6\u9891";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface 上传视频Props extends Omit<Default上传视频Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from Default上传视频Props altogether and have
// total control over the props for your component.
export interface 上传视频Props extends Default上传视频Props {}

function 上传视频_(props: 上传视频Props, ref: HTMLElementRefOf<"div">) {
  // Use Plasmic上传视频 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic上传视频 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all 上传视频Props here, but feel free
  // to do whatever works for you.

  return <Plasmic上传视频 root={{ ref }} {...props} />;
}

const 上传视频 = React.forwardRef(上传视频_);
export default 上传视频;
