// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/c_vevaluate/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/c_vevaluate/PlasmicGlobalVariant__Screen";
import { Plasmic_36小程序评估神经功能评估 } from "../components/plasmic/c_vevaluate/Plasmic_36\u5C0F\u7A0B\u5E8F\u8BC4\u4F30\u795E\u7ECF\u529F\u80FD\u8BC4\u4F30";
import { useRouter } from "next/router";

function _36小程序评估神经功能评估() {
  // Use Plasmic_36小程序评估神经功能评估 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic_36小程序评估神经功能评估 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic_36小程序评估神经功能评估 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <Plasmic_36小程序评估神经功能评估 />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default _36小程序评估神经功能评估;
