// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/c_vevaluate/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/c_vevaluate/PlasmicGlobalVariant__Screen";
import { Plasmic小程序编辑基本信息 } from "../components/plasmic/c_vevaluate/Plasmic\u5C0F\u7A0B\u5E8F\u7F16\u8F91\u57FA\u672C\u4FE1\u606F";
import { useRouter } from "next/router";

function 小程序编辑基本信息() {
  // Use Plasmic小程序编辑基本信息 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic小程序编辑基本信息 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic小程序编辑基本信息 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <Plasmic小程序编辑基本信息 />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default 小程序编辑基本信息;
