// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/c_vevaluate/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/c_vevaluate/PlasmicGlobalVariant__Screen";
import { Plasmic_37小程序上传视频 } from "../components/plasmic/c_vevaluate/Plasmic_37\u5C0F\u7A0B\u5E8F\u4E0A\u4F20\u89C6\u9891";
import { useRouter } from "next/router";

function _37小程序上传视频() {
  // Use Plasmic_37小程序上传视频 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic_37小程序上传视频 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic_37小程序上传视频 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <Plasmic_37小程序上传视频 />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default _37小程序上传视频;
